VARIABLEEEE = '1234'
VARIABLEEEE2 = '1234a'

print(VARIABLEEEE)
print(VARIABLEEEE2)

VARIABLEEEE3 = int(VARIABLEEEE)

print("tipo de VARIABLEEE : ", type(VARIABLEEEE))
print("tipo de VARIABLEEE3: ", type(VARIABLEEEE3))